server:
    port: 9909
spring:
    application:
        name: SystemsDomain
    jpa:
        database: h2
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
    datasource:
        username: sa
        password: secret
        url: jdbc:h2:mem:dev
        driverClassName: org.h2.Driver
    h2:
        console.enabled: true
        console:
            path: /h2
            settings.trace: false
            settings.web-allow-others: false
    sql:
        init:
            platform: h2
